### ISSUE TITLE
Upgrade botocore package to higher version

### ISSUE THREAD

**Issue by tin-trong-nguyen** [aws/sagemaker-tensorflow-training-toolkit#66]
The container used when creating training job seems to use `botocore == 1.10.44` - inconsistent with the version in Sagemaker Notebook instance `botocore == 1.10.50`.

Test entry point script for sagemaker training job:
```
import botocore
raise Exception(botocore.__version__)
```

Returned
```
AlgorithmError: uncaught exception during training: 1.10.44 Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start fw.train() File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 143, in train customer_script = env.import_user_module() File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 101, in import_user_module user_module = importlib.import_module(script) File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module __import__(name) File "/opt/ml/code/SM - EMLO - MultiLabel Result Screen Item Prediction.py", line 8, in <module> raise Exception(botocore.__version__) Exception: 1.10.44
```

This creates problems with using `pandas.read_csv` on `botocore.response.StreamingBody` since in the older version this class does not have __iter__() method. Entry point script that depends on `pandas.read_csv` (eg. to iterate through the training file and get the mean of each feature) that works perfectly in the notebook instance threw errors during training job, which is quite annoying.

I also tried this in the entry point script but still it doesn't work.
```
import os
os.system("pip install --upgrade botocore==1.10.50")
import botocore
```

**Comment by ChoiByungWook** [comment]
Hello,

I apologize for this problem. 

If you are using the Python SDK to make your training call, can you please try using the requirements.txt file to update botocore?
- https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/estimator.py#L161

There is also a chance that you might have to explicitly update boto3 as well. I think the version of botocore and boto3 within this container is listed here I believe. 
- https://github.com/aws/sagemaker-containers/blob/r1.0/setup.py#L41.

Let me try to see if this fixes the problem in the meantime.

**Comment by tin-trong-nguyen** [comment]
I tried the requirements_file, for some reasons it still doesn't work.

requirements_file.txt:
```
botocore >= 1.10.50
boto3 >= 1.7.50
```

entry_point:
```
import os
import numpy as np
import tensorflow as tf
import pandas as pd
import boto3
import botocore

raise Exception(botocore.__version__, boto3.__version__)
```

Log:
```
INFO:sagemaker:Creating training-job with name: sagemaker-tensorflow-2018-08-16-04-45-35-990
.................
2018-08-16 04:48:16,564 INFO - root - running container entrypoint
2018-08-16 04:48:16,564 INFO - root - starting train task
2018-08-16 04:48:16,570 INFO - container_support.training - Training starting
2018-08-16 04:48:18,089 INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTP connection (1): 169.254.170.2
2018-08-16 04:48:18,272 INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): sagemaker-bi-team.s3.amazonaws.com
2018-08-16 04:48:18,857 INFO - container_support.environment - current Python environment:
absl-py==0.2.2
astor==0.6.2
awscli==1.15.44
backports.weakref==1.0.post1
bleach==1.5.0
boto3==1.7.44
botocore==1.10.44
click==6.7
colorama==0.3.9
docutils==0.14
enum34==1.1.6
Flask==0.12.4
funcsigs==1.0.2
futures==3.2.0
gast==0.2.0
gevent==1.3.4
greenlet==0.4.13
grpcio==1.12.1
gunicorn==19.8.1
h5py==2.8.0
html5lib==0.9999999
itsdangerous==0.24
Jinja2==2.9
jmespath==0.9.3
Markdown==2.6.11
MarkupSafe==1.0
mock==2.0.0
numpy==1.14.5
pandas==0.23.1
pbr==4.0.4
Pillow==5.1.0
protobuf==3.6.0
pyasn1==0.4.3
python-dateutil==2.7.3
pytz==2018.4
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.13
sagemaker-container-support==1.0.4
sagemaker-tensorflow==1.8.0.1.0.0
sagemaker-tensorflow-container==1.0.0
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
sklearn==0.0
tensorboard==1.8.0
tensorflow==1.8.0
tensorflow-serving-api==1.7.0
termcolor==1.1.0
Werkzeug==0.14.1

2018-08-16 04:48:18,858 INFO - container_support.environment - installing requirements in /opt/ml/code/requirements_file.txt via pip
awscli 1.15.44 has requirement botocore==1.10.44, but you'll have botocore 1.10.78 which is incompatible.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2018-08-16 04:48:20,880 INFO - container_support.environment - Collecting botocore>=1.10.50 (from -r /opt/ml/code/requirements_file.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/09/c7/3a83cf3bdefc3b590872353d97857c15d7720acfa09fd9c0dec97cc2a47f/botocore-1.10.78-py2.py3-none-any.whl (4.5MB)
Collecting boto3>=1.7.50 (from -r /opt/ml/code/requirements_file.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/2d/2a/0dd8c5bc1d6e8ecac59328b155bb43b5b0d0afab8c07a03bd394ef18220c/boto3-1.7.78-py2.py3-none-any.whl (128kB)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from botocore>=1.10.50->-r /opt/ml/code/requirements_file.txt (line 1)) (0.9.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python2.7/dist-packages (from botocore>=1.10.50->-r /opt/ml/code/requirements_file.txt (line 1)) (2.7.3)
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from botocore>=1.10.50->-r /opt/ml/code/requirements_file.txt (line 1)) (0.14)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.7.50->-r /opt/ml/code/requirements_file.txt (line 2)) (0.1.13)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore>=1.10.50->-r /opt/ml/code/requirements_file.txt (line 1)) (1.11.0)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.2.0,>=0.1.10->boto3>=1.7.50->-r /opt/ml/code/requirements_file.txt (line 2)) (3.2.0)
Installing collected packages: botocore, boto3
  Found existing installation: botocore 1.10.44
    Uninstalling botocore-1.10.44:
      Successfully uninstalled botocore-1.10.44
  Found existing installation: boto3 1.7.44
    Uninstalling boto3-1.7.44:
      Successfully uninstalled boto3-1.7.44
Successfully installed boto3-1.7.78 botocore-1.10.78

2018-08-16 04:48:20,882 ERROR - container_support.training - uncaught exception during training: ('1.10.44', '1.7.44')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 143, in train
    customer_script = env.import_user_module()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 101, in import_user_module
    user_module = importlib.import_module(script)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/ml/code/SM - EMLO - MultiLabel Result Screen Item Prediction.py", line 8, in <module>
    raise Exception(botocore.__version__, boto3.__version__)
Exception: ('1.10.44', '1.7.44')



---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-140-4554ff99f475> in <module>()
     11                           train_instance_type='ml.c5.xlarge')
     12 
---> 13 tf_estimator.fit(training_dir, wait=True)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, run_tensorboard_locally)
    247                 tensorboard.join()
    248         else:
--> 249             fit_super()
    250 
    251     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    229         """
    230         def fit_super():
--> 231             super(TensorFlow, self).fit(inputs, wait, logs, job_name)
    232 
    233         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    179         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    180         if wait:
--> 181             self.latest_training_job.wait(logs=logs)
    182 
    183     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
    406     def wait(self, logs=True):
    407         if logs:
--> 408             self.sagemaker_session.logs_for_job(self.job_name, wait=True)
    409         else:
    410             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll)
    893 
    894         if wait:
--> 895             self._check_job_status(job_name, description, 'TrainingJobStatus')
    896             if dot:
    897                 print()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
    612         if status != 'Completed' and status != 'Stopped':
    613             reason = desc.get('FailureReason', '(No reason provided)')
--> 614             raise ValueError('Error training {}: {} Reason: {}'.format(job, status, reason))
    615 
    616     def wait_for_endpoint(self, endpoint, poll=5):

ValueError: Error training sagemaker-tensorflow-2018-08-16-04-45-35-990: Failed Reason: AlgorithmError: uncaught exception during training: ('1.10.44', '1.7.44')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 143, in train
    customer_script = env.import_user_module()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 101, in import_user_module
    user_module = importlib.import_module(script)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/ml/code/SM - EMLO - MultiLabel Result Screen Item Prediction.py", line 8, in <module>
    raise Exception(botocore.__version__, boto3.__version__)
Exception: ('1.10.44', '1.7.44')
```

**Comment by jesterhazy** [comment]
Unfortunately, the code in our containers that installs pip requirements files isn't able to reload already-imported modules. boto3 and bototcore are both already loaded by the time your requirements file is processed, so your training script sees the old versions even though the python packages have been updated on disk. 

We plan to fix this in a future release, but don't have an ETA right now.

If you can, try to change your pandas code (or pandas version) to something that works with the older boto versions. Or, you could isolate the code that needs the newer version into another script, and then use the `subprocess` module to run it in a separate process -- this process will see the updated boto versions.

**Comment by laurenyu** [comment]
the Dockerfiles that control what version of boto3/botocore are installed are now in https://github.com/aws/deep-learning-containers
